<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Site extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'area',
        'program',
        'uc',
        'weekHours',
        'sections',
        'info',
        'is_active',
        'is_available',
        'teachers_count',
        'last_assignment'
    ];

    protected $casts = [
        'weekHours' => 'integer',
        'sections' => 'integer',
        'is_active' => 'boolean',
        'is_available' => 'boolean',
        'teachers_count' => 'integer',
        'last_assignment' => 'datetime'
    ];

    const SITES = [
        'Acarigua/Portuguesa',
        'Achaguas/Apure',
        'Altagracia de Orituco/Guárico',
        'Amazonas',
        'Anaco/Anzoátegui',
        'Apure',
        'Barinas',
        'Barquisimeto/Lara',
        'Biscucuy',
        'Cagua/Aragua',
        'Calabozo/Guárico',
        'Camaguan/Guárico',
        'Capacho/Táchira',
        'Caracas/Distrito Capital',
        'Carora',
        'Ciudad Bolívar/Bolívar',
        'Ciudad Ojeda/Zulia',
        'Cojedes',
        'Coro/Falcón',
        'Cua/Miranda',
        'Cumaná/Sucre',
        'Distrito Capital/Caracas',
        'El Consejo/Aragua',
        'El Sombrero/Guárico',
        'El Tigre',
        'El Tocuyo/Lara',
        'Gamaguan/Guárico',
        'Guacara/Carabobo',
        'Guanare/Portuguesa',
        'Guárico/Lara',
        'Guasdualito/Apure',
        'Guasipati/Bolívar',
        'Guasipatti/Monagas',
        'Higuerote',
        'Humocaro',
        'La Guaira/Vargas',
        'La Morita/Aragua',
        'La Trinidad/Caracas',
        'La Victoria/Aragua',
        'Las Mercedes del Llano',
        'Los Teques/Miranda',
        'Mantecal',
        'Mapire',
        'Maracay/Aragua',
        'Maturín/Monagas',
        'Mérida',
        'Naguanagua/Carabobo',
        'Ortiz',
        'Palo Negro/Aragua',
        'Pariaguán/Anzoátegui',
        'Pto. Píritu',
        'Puerto Ayacucho/Amazonas',
        'Puerto Cabello/Carabobo',
        'Puerto La Cruz/Anzoátegui',
        'Puerto Ordaz/Bolívar',
        'Quíbor/Lara',
        'San Carlos/Cojedes',
        'San Cristóbal/Táchira',
        'San Felipe/Yaracuy',
        'San Fernando de Apure/Apure',
        'San José de Guanipa/Anzoátegui',
        'San José de Guaribe',
        'San Sebastián de los Reyes/Aragua',
        'Santa Cruz/Aragua',
        'Santa Rita/Maracay',
        'Sede Central/San Juan de los Morros',
        'Tinaquillo',
        'Tucupita/Delta Amacuro',
        'Turmero/Aragua',
        'Upata/Bolívar',
        'Valencia/Carabobo',
        'Valle de la Pascua/Guárico',
        'Villa de Cura/Aragua',
        'Zaraza/Guárico'
    ];

    const AREAS = [
        'Ciencias de la educación',
        'Ciencias de la salud',
        'Ciencias económicas y sociales',
        'Ciencias odontológicas',
        'Ciencias políticas y jurídicas',
        'Estudios continuos',
        'Humanidades, letras y artes',
        'Ingeniería agronómica',
        'Ingeniería de sistemas',
        'Ingeniería, arquitectura y tecnología',
        'Medicina veterinaria',
        'Post-grado',
        'Programa nacional de formación'
    ];

    const PROGRAMAS = [
        'Administración comercial',
        'Comunicación social',
        'Contaduría pública',
        'Desarrollo comunitario',
        'Doctorado ciencias de la educación',
        'Doctorado en ciencias administrativas',
        'Economía',
        'Educación continua',
        'Educación integral',
        'Educación mención computación',
        'Enfermería',
        'Enfermería mención salud comunitaria',
        'Especialización derecho administrativo',
        'Especialización en ciencias electorales',
        'Especialización en ciencias penales y criminología',
        'Especialización en derecho laboral',
        'Especialización en derecho mercantil',
        'Especialización en derecho procesal civil',
        'Especialización en dermatología',
        'Especialización en docencia universitaria',
        'Especialización en ecosonografía diagnóstica',
        'Especialización en gestión pública',
        'Especialización en medicina legal',
        'Estudios comunes',
        'Fisioterapia',
        'Hidrocarburos mención gas y mención petróleo',
        'Histocitotecnología',
        'Historia',
        'Ingeniería agronómica producción animal',
        'Ingeniería agronómica producción vegetal',
        'Ingeniería civil',
        'Ingeniería electrónica',
        'Ingeniería en informática',
        'Ingeniería industrial',
        'Licenciatura en historia',
        'Maestría en desarrollo de sistemas de producción animal',
        'Maestría en educación',
        'Maestría en educación enseñanza a la matemática',
        'Maestría en educación mención desarrollo comunitario',
        'Maestría en educación mención investigación educativa',
        'Maestría en educación mención orientación',
        'Maestría en educación mención salud comunitaria',
        'Maestría en enfermería materno infantil mención obstetricia',
        'Maestría en enfermería mención salud comunitaria',
        'Maestría en gerencia administrativa',
        'Maestría en gerencia de la construcción',
        'Maestría en gerencia de la salud pública',
        'Maestría en historia de Venezuela',
        'Maestría en salud pública',
        'Medicina',
        'Medicina veterinaria',
        'Municipalizado de formación en derecho',
        'Municipalizado de formación en derecho/misión Sucre',
        'Nutrición y dietética',
        'Odontología',
        'Optometría y óptica',
        'Profesionalización de enfermería',
        'Profesionalización de optometría',
        'Profesionalización en radioimagenología',
        'Radiodiagnóstico',
        'Radioimagenología',
        'Terapia ocupacional'
    ];

    public function teachers()
    {
        return $this->belongsToMany(Teacher::class, 'site_teacher');
    }
}
